spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/smart
    username: smart
    password: smart
  jpa:
    hibernate,ddl-auto: none
    open-in-view: false
  sql.init.mode: always
server:
  port: 0
