INSERT INTO delivery.deliveries(delivery_id,
                                country_from,
                                city_from,
                                street_from,
                                house_from,
                                flat_from,
                                country_to,
                                city_to,
                                street_to,
                                house_to,
                                flat_to,
                                order_id,
                                delivery_state)
VALUES ('1c44948b-78ca-48a5-80e5-6a901af8c117',
        'ADDRESS_1',
        'ADDRESS_1',
        'ADDRESS_1',
        'ADDRESS_1',
        'ADDRESS_1',
        'NOLAND',
        'STONE CITY',
        'FIRST LANE',
        '15',
        '42',
        'f8991fc5-1c29-4395-b781-7717893cea92',
        'CREATED');
