spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: ru.yandex.practicum.kafka.telemetry.serialization.GeneralAvroSerializer
kafka:
  topics:
    snapshots: telemetry.snapshots.v1
  event-listener:
    topics:
      - telemetry.sensors.v1
    properties:
      bootstrap.servers: localhost:9092
      group.id: telemetry.aggregators
      auto.offset.reset: earliest
      enable.auto.commit: false
logging.level:
  org.apache.kafka: WARN
