spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: ru.yandex.practicum.kafka.telemetry.serialization.GeneralAvroSerializer
    consumer:
      value-deserializer: ru.yandex.practicum.telemetry.aggregator.serialization.SensorEventDeserializer
      group-id: telemetry.aggregators
      auto-offset-reset: earliest
kafka:
  topics:
    snapshots: telemetry.snapshots.v1
    sensors: telemetry.sensors.v1
logging.level:
  org.apache.kafka: WARN
