spring:
  main.banner-mode: OFF
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql.init.mode: always
logging.level:
  ru.yandex.practicum.telemetry.analyzer.handler.snapshot: INFO
  org.hibernate.orm.jdbc.bind: INFO
