spring:
  application:
    name: analyzer
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
eureka:
  instance:
    hostname: localhost
    metadata-map:
      supported-hub-event-avro: v1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
