grpc:
  server:
    port: 0
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: ru.yandex.practicum.kafka.telemetry.serialization.GeneralAvroSerializer
kafka:
  topics:
    hubs: telemetry.hubs.v1
    sensors: telemetry.sensors.v1
logging.level:
  org.apache.kafka: WARN
